services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgresql'
    environment:
      - 'POSTGRES_DB=pitch'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
      - 'TZ=Asia/Seoul'
    ports:
      - '9000:5432'

  redis:
    image: 'redis:latest'
    container_name: 'redis'
    restart: 'always'
    hostname: 'redis'
    ports:
      - '9001:6379'