version: '3.8'

services:
  pitch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'pitch'
    environment:
      - MAIL_ADDRESS=${MAIL_ADDRESS}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - YOUTUBE_KEY=${YOUTUBE_KEY}
      - YOUTUBE_CLIENT_ID=${YOUTUBE_CLIENT_ID}
      - YOUTUBE_CLIENT_SECRET=${YOUTUBE_CLIENT_SECRET}
      - REDIRECTION_ORIGIN=${REDIRECTION_ORIGIN}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ACCESS_EXPIRATION=${JWT_ACCESS_EXPIRATION}
      - JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION}
    ports:
      - '8082:8080'
    depends_on:
      - postgres
      - redis

  postgres:
    image: 'postgres:latest'
    container_name: 'postgresql'
    restart: 'always'
    environment:
      - 'POSTGRES_DB=pitch'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
      - 'TZ=Asia/Seoul'
    ports:
      - '9000:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

  redis:
    image: 'redis:latest'
    container_name: 'redis'
    restart: 'always'
    hostname: 'redis'
    ports:
      - '9001:6379'

networks:
  default:
    driver: bridge

volumes:
  postgres_data:
    driver: local